"""The seminar's local runner.

    uv run python -m runner.server            # http://127.0.0.1:8000

One process, three jobs:

| path | does |
|---|---|
| `/` | serves the site (`site/`) |
| `/api/run` | runs a playground's code in this project's venv — real operonx, real openai SDK |
| `/mock/v1/...` | an OpenAI-compatible mock model (`site/assets/py/mockllm.py`), so every playground runs with no key |

Mode `mock` points the code's `OPENAI_BASE_URL` at `/mock/v1`; mode `real`
uses `OPENAI_API_KEY` / `OPENAI_BASE_URL` / `SEMINAR_MODEL` from `.env`.
The key never reaches the browser. Bound to 127.0.0.1: it runs whatever
code it is sent, so it must never listen on a network.
"""
from __future__ import annotations

import os
import subprocess
import sys
import time
import uuid
from pathlib import Path

from dotenv import dotenv_values
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse, RedirectResponse, Response
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

ROOT = Path(__file__).resolve().parent.parent
SITE = ROOT / "site"
RUNS = ROOT / "playground" / "runs"
PORT = int(os.environ.get("SEMINAR_PORT", "8000"))
TIMEOUT_S = 90

sys.path.insert(0, str(SITE / "assets" / "py"))
import mockllm  # noqa: E402


def write_bundle() -> None:
    """The browser runtime's Python, as a script tag can load it — `fetch` is
    blocked when the site is opened as files."""
    import json
    py = SITE / "assets" / "py"
    src = {"mockllm": (py / "mockllm.py").read_text(encoding="utf-8"),
           "openai": (py / "openai_shim.py").read_text(encoding="utf-8")}
    header = "// generated by runner/server.py from mockllm.py + openai_shim.py"
    (py / "bundle.js").write_text(header + "\nwindow.SEMINAR_PY = " + json.dumps(src) + ";\n", encoding="utf-8")


write_bundle()

app = FastAPI(title="ai-workflow-seminar runner")


def _real() -> dict:
    env = {**dotenv_values(ROOT / ".env"), **{k: v for k, v in os.environ.items() if k.startswith(("OPENAI_", "SEMINAR_"))}}
    return {k: v for k, v in env.items() if v}


# ── the mock model ───────────────────────────────────────────────────────


@app.post("/mock/v1/chat/completions")
def mock_chat(body: dict):
    return mockllm.chat(body)


@app.post("/mock/v1/embeddings")
def mock_embeddings(body: dict):
    return mockllm.embeddings(body)


# ── the runner ───────────────────────────────────────────────────────────


class Run(BaseModel):
    code: str
    mode: str = "mock"
    page: str = ""


@app.get("/api/health")
def health():
    real = _real()
    return {"ok": True, "real": bool(real.get("OPENAI_API_KEY")),
            "model": real.get("SEMINAR_MODEL", "gpt-4o-mini"),
            "base_url": real.get("OPENAI_BASE_URL", "https://api.openai.com/v1")}


@app.post("/api/run")
def run(req: Run):
    env = {k: v for k, v in os.environ.items() if not k.startswith(("OPENAI_", "SEMINAR_"))}
    env.update(PYTHONPATH=str(ROOT), PYTHONIOENCODING="utf-8", PYTHONUNBUFFERED="1",
               LOG_LEVEL="CRITICAL", LOG_USE_RICH="false",
               OPERONX_RUNS_DIR=str(ROOT / ".operonx" / "runs"))   # where Studio looks
    if req.mode == "real":
        real = _real()
        if not real.get("OPENAI_API_KEY"):
            return JSONResponse({"stdout": "", "stderr": "Real mode needs OPENAI_API_KEY in .env (see .env.example).",
                                 "exit": 2, "ms": 0}, status_code=200)
        env.update(OPENAI_API_KEY=real["OPENAI_API_KEY"],
                   OPENAI_BASE_URL=real.get("OPENAI_BASE_URL", "https://api.openai.com/v1"),
                   SEMINAR_MODEL=real.get("SEMINAR_MODEL", "gpt-4o-mini"),
                   SEMINAR_EMBED_MODEL=real.get("SEMINAR_EMBED_MODEL", "text-embedding-3-small"))
    else:
        env.update(OPENAI_API_KEY="mock-key", OPENAI_BASE_URL=f"http://127.0.0.1:{PORT}/mock/v1",
                   SEMINAR_MODEL="gpt-4o-mini", SEMINAR_EMBED_MODEL="text-embedding-3-small")
    env["SEMINAR_MODE"] = req.mode

    RUNS.mkdir(parents=True, exist_ok=True)
    name = time.strftime("%Y%m%dT%H%M%S") + "_" + (req.page or "pg") + "_" + uuid.uuid4().hex[:4]
    script = RUNS / f"{name}.py"
    script.write_text(req.code, encoding="utf-8")
    t0 = time.perf_counter()
    try:
        p = subprocess.run([sys.executable, str(script)], cwd=ROOT, env=env, capture_output=True,
                           text=True, encoding="utf-8", errors="replace", timeout=TIMEOUT_S)
        out, err, code = p.stdout, p.stderr, p.returncode
    except subprocess.TimeoutExpired as exc:
        out, err, code = (exc.stdout or ""), f"Stopped after {TIMEOUT_S} s.", 124
        out = out if isinstance(out, str) else out.decode("utf-8", "replace")
    return {"stdout": out, "stderr": err, "exit": code, "ms": round((time.perf_counter() - t0) * 1000)}


PASSWORD = os.environ.get("SEMINAR_PASSWORD", "")


@app.middleware("http")
async def password(request: Request, call_next):
    """With SEMINAR_PASSWORD set (a public tunnel), every request needs it — a tunnel
    arrives from 127.0.0.1, so the address can't tell the room from the internet.
    /mock/v1 stays open: the demo app calls it, and it only answers scripted text."""
    if PASSWORD and not request.url.path.startswith("/mock/"):
        import base64
        import secrets
        given = ""
        auth = request.headers.get("authorization", "")
        if auth.startswith("Basic "):
            try:
                given = base64.b64decode(auth[6:]).decode().partition(":")[2]
            except ValueError:
                pass
        if not secrets.compare_digest(given, PASSWORD):
            return Response("Password needed.", status_code=401,
                            headers={"WWW-Authenticate": 'Basic realm="seminar"'})
    return await call_next(request)


@app.middleware("http")
async def no_cache(request: Request, call_next):
    resp = await call_next(request)
    if request.url.path.endswith((".html", ".js", ".css", ".py")) or request.url.path == "/":
        resp.headers["Cache-Control"] = "no-store"
    return resp


@app.get("/studio")
def studio():
    return RedirectResponse("http://127.0.0.1:8766")      # Studio, opened on meeting-prep-operonx


class Send(BaseModel):
    id: str


@app.get("/api/prep/golden")
def prep_golden():
    """The golden emails the stage can send (Act 5's "Send as customer")."""
    from prep_world import golden
    return [{"id": g["id"], "from": g["from"], "subject": g["subject"], "action": g["expect"]["action"]} for g in golden()]


@app.post("/api/prep/send")
def prep_send(req: Send):
    """Send one golden email to sales, as the customer would — Mailpit's webhook does the rest."""
    from prep_world import mail
    try:
        g = mail.send_golden(req.id)
    except KeyError as e:
        return JSONResponse({"error": str(e)}, status_code=404)
    except OSError as e:
        return JSONResponse({"error": f"no mail server ({e}); is `docker compose up -d` running?"}, status_code=503)
    return {"sent": req.id, "subject": g["subject"], "from": g["from"]}


app.mount("/", StaticFiles(directory=SITE, html=True), name="site")


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="127.0.0.1", port=PORT, log_level="warning")
